#!/usr/bin/env node

var http = require ('http')
http.createServer(function(req, res) {
	res.writeHead(200, {'Content-Type': 'text/plan'});
	res.end('Hello World');
}).listen(3000);
console.log('Server running: ' + process.pid);

process.stdin.resume();

process.on('SIGINT', function() {
        console.log('Exit');
        process.exit(0);
});
