var express = require("express");
var morgan = require('morgan');
var router = require('routes/router');
var config = require('app/config');
var app = express();
app.use(morgan('short'));
app.use(router);
//app.use(error);
app.listen(config.express.port);
console.log('mongo url: %s', config.mongo.url);
console.log('Service (%d) started on port %d', config.pid, config.express.port);
